# NE PAS MODIFIER LES IMAGES PRESENTES DANS LE DOSSIER DATA. SOIT EN CREER DE NOUVELLES, SOIT EN LES COPIANT DANS UN AUTRE DOSSIER.
# TOUJOURS GARDE LES IMAGES ORIGINALES.


def main():
    print("Hello World !")

if (__name__ == "__main__"):
    main()